name: Auto-Merge Dependabot PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    permissions:
      pull-requests: write
      contents: write
      statuses: read
    steps:
      - name: Wait for all required status checks
        run: |
          echo "Waiting for status checks to complete..."
          while true; do
            STATUS=$(gh api -H "Accept: application/vnd.github+json" \
              "/repos/${{ github.repository }}/commits/${{ github.event.pull_request.head.sha }}/status" \
              --jq '.state')
            if [ "$STATUS" = "success" ]; then
              echo "✅ All required status checks passed"
              break
            elif [ "$STATUS" = "failure" ]; then
              echo "❌ One or more status checks failed"
              exit 1
            fi
            echo "⏳ Status: $STATUS - Checking again in 30 seconds..."
            sleep 30
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge Dependabot PR
        run: |
          echo "Merging PR #${{ github.event.pull_request.number }}"
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}