name: Build & Test

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  checks: write    # Required for uploading test results
  pull-requests: write   # Required for PR comments
  security-events: write # Required for CodeQL
  actions: read    # Required for checking workflow runs
  statuses: write  # Required for Codecov status updates

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8', '11', '17', '21']
      fail-fast: false

    name: Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and test
        run: mvn --ntp -B verify

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-java-${{ matrix.java }}
          path: '**/target/surefire-reports/'

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-java-${{ matrix.java }}
          path: '**/target/site/jacoco/'

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage reports to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
