name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]'
      - 'V?[0-9]+.[0-9]+.[0-9]'
      - 'v?[0-9]+.[0-9]+.[0-9]+-SNAPSHOT'
      - 'V?[0-9]+.[0-9]+.[0-9]+-SNAPSHOT'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Set version from tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "Setting version to $VERSION"
          mvn -B versions:set -DnewVersion=$VERSION -DgenerateBackupPoms=false | awk '/svaningelgem/ || !/Downloading|Downloaded|Progress/'

      - name: Building
        run: |
          set -o pipefail
          mvn --ntp -B clean install | awk '/svaningelgem/ || !/Downloading|Downloaded|Progress/'

      - name: Flatten pom.xml file
        run: |
          set -o pipefail
          mvn --ntp -B flatten:flatten | awk '/svaningelgem/ || !/Downloading|Downloaded|Progress/'

      - name: Deploying to Central
        run: |
          set -o pipefail
          mvn -B deploy -pl jacoco-console-reporter -am -P release -DskipTests | awk '/svaningelgem/ || !/Downloading|Downloaded|Progress/'
        env:
          MAVEN_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            jacoco-console-reporter/target/*.jar
          generate_release_notes: true
          make_latest: true
          fail_on_unmatched_files: false
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
