# .github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
          server-id: github

      - name: Build with Maven
        run: mvn -B package

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            **/target/*.jar
            !**/target/*-sources.jar
            !**/target/*-javadoc.jar
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
